#postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata: 
  name: postgres-secret
type: Opaque
data:
  postgres-username: changethis
  postgres-password: changethis
  postgres-database: changethis