---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fastapi-secret
  namespace: grocery-ocr-api
spec:
  encryptedData:
    url: AgBsNvl2U0kdq/QLIU9Li9zmKVqhW3iqoYRPUGoMBygyFjnVyzvKM/Hi37lAQMX4t0JEEhRkZU1qNizVZKvDCFOTzuebdMK0Wvop7fapeLQZPoTxv+2CacZmfd14/89YEZW74LF2CuaS+HXPHnXSYJBuLwKlqjsOFqGpXSkHqFG4GiZJlgi2MSpqLdTKArJSVK9IiSwv8RBhCi7Aus31CsNoxUj8XQBeYjhwWbuYWd4t6UscsuTrR4bmvqVPBjR3UY6gbqTfa4eB8XXd3qyTdyEEPXayhKg58H9PwiSFvuE0hRb6IqsUDL7P0T3tOKG5BcIBP16YHL9lYOZB2P8JVwcsBLh4s05LqrP7dCc/M6gTy7IZYXXHbDtv5jdMw33lZ17xYFOS4JYUgK2OWngKBtLVuoijdHv60TXn9d5bU6l5hfnR/Aa7/OLnt79Ovz3h16GxxOgSqyHcVOmJJfT9byZ0lNYrLsvOoBkj4vbxw+5Umu003isFIlFxXjn1nh2ucfGcSrV9QID2XV+IGwFkikK5E74+QalcCU4pooWxSA5fy8cinP+Y0i8LsHIi683YSBE1bb27lccJwTCnD7IeoygFxyLwgCrq57pY4cVOeiLZ4H27DY59AEmRqdcaQ7IJ1qfKH5qrRiw5BiL9zBkkp1qPqt6tbNTRWTILYo0hU8TsdeZjowApEWqjOiLOrkx70agj1r9FWO1iMs1v7AzskyNsodFgc+et2cnGXkY6KCQ2bCBMNcugfqDMCGIjxP20BbGQsUt/XQSy+7wq1Bpvyt/6dHXn/A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi
      name: fastapi-secret
      namespace: grocery-ocr-api
